### ISSUE TITLE
Move last 1 commit from community PR#6851 to cloud repo

### ISSUE THREAD

**Issue by hluchas** [mautic-inc/plugin-slooce#6]
PR:
https://github.com/mautic/mautic/pull/6851

commits:
a17353d744ecd4c470f4d532cd69d869b5d38e12

Depends on our issue https://github.com/mautic-inc/mautic-internal/issues/149 - after merge

**Comment by alanhartless** [comment]
@hluchas is this critical? If not let's close this as we'll pick it up the next time we merge community back into our code base.

**Comment by hluchas** [comment]
not critical
