### ISSUE TITLE
Gettting error while installing this plugin

### ISSUE THREAD

**Issue by tssmahendra** [mautic-inc/plugin-slooce#9]
I m getting this error
 Class 'MauticPlugin\IntegrationsBundle\Integration\BasicIntegration' not found in mautic/plugins/MauticSlooceTransportBundle/Integration/SlooceIntegration.php on line 25 while installing this plugin

**Comment by alanhartless** [comment]
Hi,

It requires https://github.com/mautic-inc/plugin-mautic-integrations (listed as the third requirement in the readme :-)
